"""Phrase inventory for the rule-based reference agent.

This module is the single source of truth for what the reference agent understands.
Scenario authors must stay inside it (plus the menu aliases). Every phrase is stored
already normalised (lowercase, punctuation replaced by spaces), so ``"that's all"`` appears
as ``"that s all"``. Languages are ``"en-IN"`` and ``"hi-en"``.
"""

from __future__ import annotations

_DIGITS = {str(n): n for n in range(1, 11)}

# Number words per language. "do" means two only in Hinglish (in English it is a verb) and
# the articles "a"/"an" mean one only in English.
NUMBER_WORDS: dict[str, dict[str, int]] = {
    "en-IN": {
        "a": 1,
        "an": 1,
        "one": 1,
        "single": 1,
        "two": 2,
        "three": 3,
        "four": 4,
        "five": 5,
        "six": 6,
        "ek": 1,
        "teen": 3,
        **_DIGITS,
    },
    "hi-en": {
        "ek": 1,
        "do": 2,
        "teen": 3,
        "char": 4,
        "chaar": 4,
        "paanch": 5,
        "panch": 5,
        "che": 6,
        "chhe": 6,
        "one": 1,
        "two": 2,
        "three": 3,
        "four": 4,
        "five": 5,
        "six": 6,
        **_DIGITS,
    },
}

# Phrases that always mean a quantity of one.
QUANTITY_PHRASES: dict[str, int] = {"ek hi": 1, "one only": 1, "only one": 1, "sirf ek": 1}

# In Hinglish, "do" right after one of these verb stems is the verb "give/do" ("de do",
# "kar do"), never the number two.
DO_VERB_STEMS: list[str] = [
    "de",
    "kar",
    "bhej",
    "laga",
    "dal",
    "daal",
    "rakh",
    "bana",
    "hata",
    "nikal",
    "nikaal",
    "badal",
    "mat",
    "add",
    "order",
    "place",
    "cancel",
    "remove",
    "le",
]

CONNECTORS: list[str] = ["and also", "and", "aur", "also", "plus", "then", "phir"]

CORRECTION_MARKERS: list[str] = [
    "actually",
    "wait",
    "sorry",
    "no wait",
    "instead",
    "make it",
    "make that",
    "make them",
    "change it to",
    "change that to",
    "change to",
    "nahi nahi",
    "nahi",
    "badal do",
    "badal ke",
    "ki jagah",
    "rehne do",
    "correction",
    "i meant",
    "matlab",
    "scratch that",
]

REMOVE_MARKERS: list[str] = [
    "remove",
    "take off",
    "hata do",
    "hata",
    "nikal do",
    "nikaal do",
    "mat do",
    "nahi chahiye",
    "don t want",
    "do not want",
    "dont want",
    "drop",
    "skip",
    "cancel the",
    "cancel that",
    "cancel",
]

CANCEL_ORDER_MARKERS: list[str] = [
    "cancel the order",
    "cancel my order",
    "cancel the whole order",
    "cancel everything",
    "cancel it all",
    "cancel order",
    "order cancel",
    "poora order cancel",
    "pura order cancel",
    "sab cancel",
    "sab kuch cancel",
    "order cancel kar do",
    "cancel kar do poora",
]

CLOSING_MARKERS: list[str] = [
    "that s all",
    "thats all",
    "that is all",
    "that s it",
    "thats it",
    "that will be all",
    "that ll be all",
    "nothing else",
    "that s everything",
    "bas",
    "bas itna hi",
    "itna hi",
    "aur kuch nahi",
    "bas yahi",
    "ho gaya",
    "done",
    "i m done",
]

CONFIRM_MARKERS: list[str] = [
    "yes",
    "yeah",
    "yep",
    "yup",
    "haan",
    "ha",
    "ji",
    "ji haan",
    "ok",
    "okay",
    "theek hai",
    "sahi hai",
    "confirm",
    "confirmed",
    "go ahead",
    "place it",
    "place the order",
    "order kar do",
    "order place kar do",
    "correct",
    "right",
    "sure",
    "please place the order",
    "that s right",
    "thats right",
    "that is right",
    "that s correct",
    "confirm kar do",
    "place kar do",
]

QUESTION_MARKERS: list[str] = [
    "which",
    "what",
    "how many",
    "kitne",
    "kitna",
    "konsa",
    "kaunsa",
    "kya",
    "would you like",
    "do you want",
    "chahiye",
]

# The caller asks the agent to read the order back or whether it went through.
READBACK_MARKERS: list[str] = [
    "repeat",
    "read it back",
    "read that back",
    "read the order back",
    "read my order back",
    "what did i order",
    "what do you have",
    "what have you got",
    "did my order go through",
    "did the order go through",
    "did you get my order",
    "did you get that",
    "is my order placed",
    "has my order been placed",
    "order ho gaya kya",
    "order gaya kya",
    "order place hua",
    "order mila",
    "dobara bolo",
    "ek baar bolo",
    "ek baar batao",
]

# A clause that is only a bare negation, politeness or greeting produces no clause at all.
IGNORED_CLAUSES: list[str] = [
    "no",
    "nahi",
    "nope",
    "no thanks",
    "thanks",
    "thank you",
    "please",
    "ok bye",
    "okay bye",
    "bye",
    "hello",
    "hi",
    "are you there",
    "sun rahe ho",
    "sunai de raha hai",
    "hmm",
    "umm",
    "uh",
    "haan ji",
]

# Words stripped before deciding that a clause is a pure confirmation.
CONFIRM_FILLERS: list[str] = [
    "please",
    "now",
    "ab",
    "thanks",
    "thank you",
    "kripya",
    "bhaiya",
    "bhai",
    "sir",
    "ma am",
]

# Words that may accompany a bare quantity or modifier without making the clause unknown
# ("ek hi karo", "make them spicy", "no onion please").
CORRECTION_FILLERS: list[str] = [
    "karo",
    "kar do",
    "kar dena",
    "kar dijiye",
    "kar",
    "rakho",
    "rakh do",
    "rakhna",
    "dena",
    "de do",
    "dijiye",
    "chahiye",
    "please",
    "only",
    "just",
    "hi",
    "the",
    "them",
    "it",
    "that",
    "those",
    "these",
    "with",
    "ke saath",
    "wala",
    "wali",
    "wale",
    "ones",
    "mujhe",
    "for me",
    "to",
    "of",
    "bas",
    "hai",
    "ho",
    "me",
    "mein",
    "my",
    "mera",
    "meri",
    "on",
    "in",
    "sab",
    "all",
    "both",
    "dono",
    "and",
    "aur",
    "pieces",
    "piece",
    "plates",
    "plate",
    "cups",
    "cup",
    "glasses",
    "glass",
    "zyada",
    "aur ek",
    "more",
    "another",
    "ek aur",
    "one more",
    "same",
    "wahi",
]
